using NUnit.Framework;
using UnityEditor.UIElements;
using UnityEngine;
using UnityEngine.UIElements;

namespace UnitySvgEditor.Editor.Tests
{
    public sealed class InspectorModelReadPathTests
    {
        [Test]
        public void RefreshTargets_UsesDocumentModelForCurrentDocumentReadPath()
        {
            const string sourceText = "<svg xmlns=\"http://www.w3.org/2000/svg\"><rect id=\"node\" transform=\"translate(1 1)\" /></svg>";
            const string modelSource = "<svg xmlns=\"http://www.w3.org/2000/svg\"><rect id=\"node\" transform=\"translate(9 4)\" /></svg>";

            var host = new FakeInspectorPanelHost
            {
                CurrentDocument = new DocumentSession
                {
                    WorkingSourceText = sourceText,
                    DocumentModel = SvgFixtureTestUtility.LoadModel(modelSource)
                }
            };

            var view = new InspectorPanelView();
            var state = new InspectorPanelState();
            var service = new InspectorTargetSyncService(new AttributePatcher(), state, view, () => host, null);
            var root = CreateInspectorRoot();
            view.Bind(root);

            service.RefreshTargets(sourceText);
            Assert.That(service.TrySelectTargetByKey("node", out _), Is.True);
            service.RefreshTargets(sourceText);

            Assert.That(root.Q<FloatField>("inspector-translate-x").value, Is.EqualTo(9f).Within(0.001f));
            Assert.That(root.Q<FloatField>("inspector-translate-y").value, Is.EqualTo(4f).Within(0.001f));
        }

        [Test]
        public void RefreshTargets_UsesDocumentModelForAutoGeneratedTargetKeys()
        {
            const string sourceText = "<svg xmlns=\"http://www.w3.org/2000/svg\"><rect transform=\"translate(1 1)\" /></svg>";
            const string modelSource = "<svg xmlns=\"http://www.w3.org/2000/svg\"><rect transform=\"translate(11 6)\" /></svg>";
            const string autoTargetKey = "__auto__:svg[0]/rect[0]";

            var host = new FakeInspectorPanelHost
            {
                CurrentDocument = new DocumentSession
                {
                    WorkingSourceText = sourceText,
                    DocumentModel = SvgFixtureTestUtility.LoadModel(modelSource)
                }
            };

            var view = new InspectorPanelView();
            var state = new InspectorPanelState();
            var service = new InspectorTargetSyncService(new AttributePatcher(), state, view, () => host, null);
            var root = CreateInspectorRoot();
            view.Bind(root);

            service.RefreshTargets(sourceText);
            Assert.That(service.TrySelectTargetByKey(autoTargetKey, out _), Is.True);
            service.RefreshTargets(sourceText);

            Assert.That(root.Q<FloatField>("inspector-translate-x").value, Is.EqualTo(11f).Within(0.001f));
            Assert.That(root.Q<FloatField>("inspector-translate-y").value, Is.EqualTo(6f).Within(0.001f));
        }

        private static VisualElement CreateInspectorRoot()
        {
            var root = new VisualElement();
            root.Add(new DropdownField { name = "patch-target" });
            root.Add(new FloatField { name = "inspector-frame-x" });
            root.Add(new FloatField { name = "inspector-frame-y" });
            root.Add(new FloatField { name = "inspector-frame-width" });
            root.Add(new FloatField { name = "inspector-frame-height" });
            root.Add(new FloatField { name = "inspector-translate-x" });
            root.Add(new FloatField { name = "inspector-translate-y" });
            root.Add(new FloatField { name = "inspector-rotate" });
            root.Add(new FloatField { name = "inspector-scale-x", value = 1f });
            root.Add(new FloatField { name = "inspector-scale-y", value = 1f });
            root.Add(new TextField { name = "inspector-transform" });
            return root;
        }

        private sealed class FakeInspectorPanelHost : IInspectorPanelHost
        {
            public DocumentSession CurrentDocument { get; set; }

            public bool TryApplyPatchRequest(AttributePatchRequest request, string successStatus)
            {
                return true;
            }

            public bool TryApplyTargetFrameRect(string targetKey, Rect targetSceneRect, string successStatus)
            {
                return true;
            }

            public bool TryGetTargetSceneRect(string targetKey, out Rect sceneRect)
            {
                sceneRect = default;
                return false;
            }

            public void SyncSelectionFromInspectorTarget(string targetKey)
            {
            }

            public void UpdateSourceStatus(string status)
            {
            }
        }
    }
}
