using System.Collections.Generic;
using System.Linq;
using NUnit.Framework;

namespace UnitySvgEditor.Editor.Tests
{
    public sealed class StructureDocumentModelReaderTests
    {
        [Test]
        public void TryBuildSnapshot_PreservesHierarchyShapeFromModel()
        {
            SvgDocumentModel documentModel = SvgFixtureTestUtility.LoadFixtureModel("transformed-parent.svg");

            bool success = StructureDocumentModelReader.TryBuildSnapshot(documentModel, out StructureOutline snapshot, out string error);

            Assert.That(success, Is.True, error);
            Assert.That(snapshot.Elements.Count, Is.EqualTo(6));
            Assert.That(snapshot.HierarchyItems.Count, Is.EqualTo(1));
            Assert.That(snapshot.HierarchyItems[0].data.Key, Is.EqualTo("__auto__:svg[0]"));
            Assert.That(snapshot.HierarchyItems[0].children.Count, Is.EqualTo(2));

            StructureNode groupNode = snapshot.Elements.First(node => node.Key == "parent-group");
            StructureNode childPathNode = snapshot.Elements.First(node => node.Key == "child-path");

            Assert.That(groupNode.ParentKey, Is.EqualTo("__auto__:svg[0]"));
            Assert.That(groupNode.Depth, Is.EqualTo(1));
            Assert.That(childPathNode.ParentKey, Is.EqualTo("parent-group"));
            Assert.That(childPathNode.Depth, Is.EqualTo(2));
        }

        [Test]
        public void TryBuildSnapshot_PreservesAutoGeneratedLegacyKeys()
        {
            SvgDocumentModel documentModel = SvgFixtureTestUtility.LoadFixtureModel("no-viewbox-basic.svg");

            bool success = StructureDocumentModelReader.TryBuildSnapshot(documentModel, out StructureOutline snapshot, out string error);

            Assert.That(success, Is.True, error);
            Assert.That(snapshot.Elements.Any(node => node.Key == "__auto__:svg[0]/rect[0]" && node.TargetKey == "__auto__:svg[0]/rect[0]"), Is.True);
        }

        [Test]
        public void TryBuildSnapshot_BuildsLayerSummaryAndLayerKeys()
        {
            const string source = "<svg xmlns=\"http://www.w3.org/2000/svg\"><g id=\"layer-a\" display=\"none\"><rect id=\"inside-layer\" width=\"10\" height=\"12\" /></g><rect id=\"outside-layer\" width=\"3\" height=\"4\" /></svg>";
            SvgDocumentModel documentModel = SvgFixtureTestUtility.LoadModel(source);

            bool success = StructureDocumentModelReader.TryBuildSnapshot(documentModel, out StructureOutline snapshot, out string error);

            Assert.That(success, Is.True, error);
            Assert.That(snapshot.Layers.Count, Is.EqualTo(1));
            Assert.That(snapshot.Layers[0].Key, Is.EqualTo("layer-a"));
            Assert.That(snapshot.Layers[0].DisplayName, Is.EqualTo("#layer-a"));
            Assert.That(snapshot.Layers[0].IsVisible, Is.False);
            Assert.That(snapshot.Layers[0].ElementCount, Is.EqualTo(1));

            StructureNode insideLayerNode = snapshot.Elements.First(node => node.Key == "inside-layer");
            StructureNode outsideLayerNode = snapshot.Elements.First(node => node.Key == "outside-layer");

            Assert.That(insideLayerNode.LayerKey, Is.EqualTo("layer-a"));
            Assert.That(outsideLayerNode.LayerKey, Is.Empty);
        }
    }
}
